"use strict";
/* The library of quotations — revealed word by word, like ink appearing
   on the page. A folio's quote is chosen at random from the entries not
   yet used; only after every quote has appeared does the cycle begin
   again (a tiny on-device list in localStorage keeps the rotation —
   nothing ever leaves the machine). */
const QUOTES = [
  {t:"Simplicity is the ultimate sophistication.", a:"Leonardo da Vinci"},
  {t:"Learning never exhausts the mind.", a:"Leonardo da Vinci"},
  {t:"Art is never finished, only abandoned.", a:"Leonardo da Vinci"},
  {t:"The noblest pleasure is the joy of understanding.", a:"Leonardo da Vinci"},
  {t:"Water is the driving force of all nature.", a:"Leonardo da Vinci"},
  {t:"Time stays long enough for anyone who will use it.", a:"Leonardo da Vinci"},
  {t:"We know what we are, but know not what we may be.", a:"William Shakespeare"},
  {t:"There is nothing either good or bad, but thinking makes it so.", a:"William Shakespeare"},
  {t:"Our doubts are traitors, and make us lose the good we oft might win by fearing to attempt.", a:"William Shakespeare"},
  {t:"Love all, trust a few, do wrong to none.", a:"William Shakespeare"},
  {t:"To thine own self be true.", a:"William Shakespeare"},
  {t:"The course of true love never did run smooth.", a:"William Shakespeare"},
  {t:"Be yourself; everyone else is already taken.", a:"Oscar Wilde"},
  {t:"We are all in the gutter, but some of us are looking at the stars.", a:"Oscar Wilde"},
  {t:"To live is the rarest thing in the world. Most people exist, that is all.", a:"Oscar Wilde"},
  {t:"Experience is simply the name we give our mistakes.", a:"Oscar Wilde"},
  {t:"Kindness is the language which the deaf can hear and the blind can see.", a:"Mark Twain"},
  {t:"The secret of getting ahead is getting started.", a:"Mark Twain"},
  {t:"Continuous improvement is better than delayed perfection.", a:"Mark Twain"},
  {t:"Do not go where the path may lead, go instead where there is no path and leave a trail.", a:"Ralph Waldo Emerson"},
  {t:"What lies behind us and what lies before us are tiny matters compared to what lies within us.", a:"Ralph Waldo Emerson"},
  {t:"Adopt the pace of nature: her secret is patience.", a:"Ralph Waldo Emerson"},
  {t:"Go confidently in the direction of your dreams. Live the life you have imagined.", a:"Henry David Thoreau"},
  {t:"The world is but a canvas to our imagination.", a:"Henry David Thoreau"},
  {t:"It's not what you look at that matters, it's what you see.", a:"Henry David Thoreau"},
  {t:"Keep your face always toward the sunshine, and shadows will fall behind you.", a:"Walt Whitman"},
  {t:"I am large, I contain multitudes.", a:"Walt Whitman"},
  {t:"Hope is the thing with feathers that perches in the soul.", a:"Emily Dickinson"},
  {t:"Forever is composed of nows.", a:"Emily Dickinson"},
  {t:"I dwell in possibility.", a:"Emily Dickinson"},
  {t:"A thing of beauty is a joy for ever.", a:"John Keats"},
  {t:"Heard melodies are sweet, but those unheard are sweeter.", a:"John Keats"},
  {t:"To see a world in a grain of sand, and a heaven in a wild flower.", a:"William Blake"},
  {t:"No bird soars too high if he soars with his own wings.", a:"William Blake"},
  {t:"What you seek is seeking you.", a:"Rumi"},
  {t:"The wound is the place where the light enters you.", a:"Rumi"},
  {t:"Raise your words, not voice. It is rain that grows flowers, not thunder.", a:"Rumi"},
  {t:"You were born with wings, why prefer to crawl through life?", a:"Rumi"},
  {t:"It is not that we have a short time to live, but that we waste a lot of it.", a:"Seneca"},
  {t:"Luck is what happens when preparation meets opportunity.", a:"Seneca"},
  {t:"Every new beginning comes from some other beginning's end.", a:"Seneca"},
  {t:"You have power over your mind — not outside events. Realize this, and you will find strength.", a:"Marcus Aurelius"},
  {t:"The soul becomes dyed with the color of its thoughts.", a:"Marcus Aurelius"},
  {t:"Waste no more time arguing about what a good man should be. Be one.", a:"Marcus Aurelius"},
  {t:"No man is free who is not master of himself.", a:"Epictetus"},
  {t:"It's not what happens to you, but how you react to it that matters.", a:"Epictetus"},
  {t:"The beginning is the most important part of the work.", a:"Plato"},
  {t:"Wise men speak because they have something to say; fools because they have to say something.", a:"Plato"},
  {t:"Knowing yourself is the beginning of all wisdom.", a:"Aristotle"},
  {t:"The whole is greater than the sum of its parts.", a:"Aristotle"},
  {t:"We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a:"Aristotle"},
  {t:"It does not matter how slowly you go as long as you do not stop.", a:"Confucius"},
  {t:"Everything has beauty, but not everyone sees it.", a:"Confucius"},
  {t:"The man who moves a mountain begins by carrying away small stones.", a:"Confucius"},
  {t:"A journey of a thousand miles begins with a single step.", a:"Lao Tzu"},
  {t:"Nature does not hurry, yet everything is accomplished.", a:"Lao Tzu"},
  {t:"When I let go of what I am, I become what I might be.", a:"Lao Tzu"},
  {t:"Everyone thinks of changing the world, but no one thinks of changing himself.", a:"Leo Tolstoy"},
  {t:"The two most powerful warriors are patience and time.", a:"Leo Tolstoy"},
  {t:"If you want to be happy, be.", a:"Leo Tolstoy"},
  {t:"Beauty will save the world.", a:"Fyodor Dostoevsky"},
  {t:"To live without hope is to cease to live.", a:"Fyodor Dostoevsky"},
  {t:"Don't tell me the moon is shining; show me the glint of light on broken glass.", a:"Anton Chekhov"},
  {t:"Knowledge is of no value unless you put it into practice.", a:"Anton Chekhov"},
  {t:"Even the darkest night will end and the sun will rise.", a:"Victor Hugo"},
  {t:"Music expresses that which cannot be put into words and that which cannot remain silent.", a:"Victor Hugo"},
  {t:"He who opens a school door, closes a prison.", a:"Victor Hugo"},
  {t:"Whatever you can do or dream you can, begin it. Boldness has genius, power and magic in it.", a:"Johann Wolfgang von Goethe"},
  {t:"Magic is believing in yourself. If you can do that, you can make anything happen.", a:"Johann Wolfgang von Goethe"},
  {t:"Knowing is not enough; we must apply. Willing is not enough; we must do.", a:"Johann Wolfgang von Goethe"},
  {t:"He who has a why to live can bear almost any how.", a:"Friedrich Nietzsche"},
  {t:"You must have chaos within you to give birth to a dancing star.", a:"Friedrich Nietzsche"},
  {t:"Paths are made by walking.", a:"Franz Kafka"},
  {t:"A book must be the axe for the frozen sea within us.", a:"Franz Kafka"},
  {t:"No need to hurry. No need to sparkle. No need to be anybody but oneself.", a:"Virginia Woolf"},
  {t:"Books are the mirrors of the soul.", a:"Virginia Woolf"},
  {t:"The world breaks everyone, and afterward, some are strong at the broken places.", a:"Ernest Hemingway"},
  {t:"Try to be a rainbow in someone's cloud.", a:"Maya Angelou"},
  {t:"Nothing will work unless you do.", a:"Maya Angelou"},
  {t:"We may encounter many defeats but we must not be defeated.", a:"Maya Angelou"},
  {t:"Courage, dear heart.", a:"C. S. Lewis"},
  {t:"You are never too old to set another goal or to dream a new dream.", a:"C. S. Lewis"},
  {t:"Not all those who wander are lost.", a:"J. R. R. Tolkien"},
  {t:"Even the smallest person can change the course of the future.", a:"J. R. R. Tolkien"},
  {t:"All we have to decide is what to do with the time that is given us.", a:"J. R. R. Tolkien"},
  {t:"It is our choices that show what we truly are, far more than our abilities.", a:"J. K. Rowling"},
  {t:"Those who don't believe in magic will never find it.", a:"Roald Dahl"},
  {t:"Imagination is more important than knowledge.", a:"Albert Einstein"},
  {t:"Look deep into nature, and then you will understand everything better.", a:"Albert Einstein"},
  {t:"In the middle of difficulty lies opportunity.", a:"Albert Einstein"},
  {t:"Nothing in life is to be feared, it is only to be understood.", a:"Marie Curie"},
  {t:"Great things are done by a series of small things brought together.", a:"Vincent van Gogh"},
  {t:"I dream my painting and I paint my dream.", a:"Vincent van Gogh"},
  {t:"If you hear a voice within you say 'you cannot paint,' then by all means paint, and that voice will be silenced.", a:"Vincent van Gogh"},
  {t:"I saw the angel in the marble and carved until I set him free.", a:"Michelangelo"},
  {t:"The greater danger is not that our aim is too high and we miss it, but that it is too low and we reach it.", a:"Michelangelo"},
  {t:"Two roads diverged in a wood, and I — I took the one less traveled by.", a:"Robert Frost"},
  {t:"In three words I can sum up everything I've learned about life: it goes on.", a:"Robert Frost"},
  {t:"The best way out is always through.", a:"Robert Frost"},
  {t:"Faith is the bird that feels the light when the dawn is still dark.", a:"Rabindranath Tagore"},
  {t:"You can't cross the sea merely by standing and staring at the water.", a:"Rabindranath Tagore"},
  {t:"You can cut all the flowers but you cannot keep spring from coming.", a:"Pablo Neruda"},
  {t:"I have always imagined that Paradise will be a kind of library.", a:"Jorge Luis Borges"},
  {t:"No one is useless in this world who lightens the burdens of another.", a:"Charles Dickens"},
  {t:"Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.", a:"Charles Dickens"},
  {t:"I am no bird; and no net ensnares me: I am a free human being with an independent will.", a:"Charlotte Brontë"},
  {t:"I am not afraid of storms, for I am learning how to sail my ship.", a:"Louisa May Alcott"},
  {t:"Why, sometimes I've believed as many as six impossible things before breakfast.", a:"Lewis Carroll"},
  {t:"Anything one man can imagine, other men can make real.", a:"Jules Verne"},
  {t:"It is only with the heart that one can see rightly; what is essential is invisible to the eye.", a:"Antoine de Saint-Exupéry"},
  {t:"In the depth of winter, I finally learned that within me there lay an invincible summer.", a:"Albert Camus"},
  {t:"Out of suffering have emerged the strongest souls.", a:"Kahlil Gibran"},
  {t:"Life can only be understood backwards; but it must be lived forwards.", a:"Søren Kierkegaard"},
  {t:"Judge a man by his questions rather than by his answers.", a:"Voltaire"},
  {t:"The heart has its reasons which reason knows nothing of.", a:"Blaise Pascal"},
  {t:"The greatest thing in the world is to know how to belong to oneself.", a:"Michel de Montaigne"},
  {t:"No man ever steps in the same river twice.", a:"Heraclitus"},
  {t:"In the midst of chaos, there is also opportunity.", a:"Sun Tzu"},
  {t:"Do not seek to follow in the footsteps of the wise; seek what they sought.", a:"Matsuo Bashō"},
  {t:"Dripping water hollows out stone, not through force but through persistence.", a:"Ovid"},
  {t:"Fortune favors the bold.", a:"Virgil"},
  {t:"The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", a:"John Milton"},
  {t:"No man is an island, entire of itself.", a:"John Donne"},
  {t:"To err is human; to forgive, divine.", a:"Alexander Pope"},
  {t:"Vision is the art of seeing what is invisible to others.", a:"Jonathan Swift"},
  {t:"Well done is better than well said.", a:"Benjamin Franklin"},
  {t:"Energy and persistence conquer all things.", a:"Benjamin Franklin"},
  {t:"Genius is one percent inspiration and ninety-nine percent perspiration.", a:"Thomas Edison"},
  {t:"If I have seen further it is by standing on the shoulders of giants.", a:"Isaac Newton"},
  {t:"Life is short, and art long.", a:"Hippocrates"},
  {t:"The pen is the tongue of the mind.", a:"Miguel de Cervantes"},
  {t:"Whatever our souls are made of, his and mine are the same.", a:"Emily Brontë"},
  {t:"Quality is never an accident; it is always the result of intelligent effort.", a:"John Ruskin"},
  {t:"The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", a:"Marcel Proust"},
  {t:"Let everything happen to you: beauty and terror. Just keep going. No feeling is final.", a:"Rainer Maria Rilke"},
  {t:"The only journey is the one within.", a:"Rainer Maria Rilke"},
  {t:"Within you there is a stillness and a sanctuary to which you can retreat at any time.", a:"Hermann Hesse"},
  {t:"The world is full of magic things, patiently waiting for our senses to grow sharper.", a:"W. B. Yeats"},
  {t:"Life isn't about finding yourself. Life is about creating yourself.", a:"George Bernard Shaw"},
  {t:"Progress is impossible without change.", a:"George Bernard Shaw"},
  {t:"Fairy tales tell us that dragons can be beaten.", a:"G. K. Chesterton"},
  {t:"Not everything that is faced can be changed, but nothing can be changed until it is faced.", a:"James Baldwin"},
  {t:"There are years that ask questions and years that answer.", a:"Zora Neale Hurston"},
  {t:"So we beat on, boats against the current, borne back ceaselessly into the past.", a:"F. Scott Fitzgerald"},
  {t:"And now that you don't have to be perfect, you can be good.", a:"John Steinbeck"},
  {t:"I took a deep breath and listened to the old brag of my heart: I am, I am, I am.", a:"Sylvia Plath"},
  {t:"We are what we pretend to be, so we must be careful about what we pretend to be.", a:"Kurt Vonnegut"},
  {t:"You fail only if you stop writing.", a:"Ray Bradbury"},
  {t:"It is good to have an end to journey toward; but it is the journey that matters, in the end.", a:"Ursula K. Le Guin"},
  {t:"It is not true that people stop pursuing dreams because they grow old; they grow old because they stop pursuing dreams.", a:"Gabriel García Márquez"},
];
