"use strict";
/* The library of quotations — revealed word by word, like ink appearing
   on the page. Sources are classic, public-domain works, quoted from
   public-domain translations (Butler and Pope for Homer, Garnett for
   Dostoevsky, standard renderings for the Gita, Chanakya Niti and the
   Shiva Purana) and attributed to author and work. A quote is used only
   once until the whole library has been read; only then does the cycle
   restart (a tiny on-device list in localStorage keeps the rotation —
   nothing ever leaves the machine). */
const QUOTES = [
  /* ---------------- Homer — The Iliad ---------------- */
  {t:"Like the generations of leaves, so are those of men; the wind scatters the leaves on the ground, and the forest puts forth others as spring comes round.", a:"Homer · The Iliad"},
  {t:"Hateful to me as the gates of Hades is that man who hides one thing in his heart and speaks another.", a:"Homer · The Iliad"},
  {t:"Be both a speaker of words and a doer of deeds.", a:"Homer · The Iliad"},
  {t:"No man can hurry me down to Hades before my time; as for fate, no man alive has ever escaped it, neither brave man nor coward.", a:"Homer · The Iliad"},
  {t:"To one man a god has given deeds of war, to another the dance, to another the lyre and song.", a:"Homer · The Iliad"},
  {t:"A councillor ought not to sleep the whole night through — a man to whom the people are entrusted, and who has many cares.", a:"Homer · The Iliad"},
  {t:"Even a fool may be wise after the event.", a:"Homer · The Iliad"},
  {t:"Light is the task where many share the toil.", a:"Homer · The Iliad"},
  {t:"Zeus does not bring all men's plans to fulfillment.", a:"Homer · The Iliad"},
  {t:"The fates have given mankind an enduring heart.", a:"Homer · The Iliad"},
  /* ---------------- Homer — The Odyssey ---------------- */
  {t:"There is nothing better or finer than when man and wife keep house together with one heart and one mind.", a:"Homer · The Odyssey"},
  {t:"Of all creatures that breathe and move upon the earth, nothing is bred that is weaker than man.", a:"Homer · The Odyssey"},
  {t:"There is a time for many words, and there is also a time for sleep.", a:"Homer · The Odyssey"},
  {t:"Nothing is sweeter in the end than one's own country and one's own parents.", a:"Homer · The Odyssey"},
  {t:"Even his griefs are a joy long after, to one that remembers all that he wrought and endured.", a:"Homer · The Odyssey"},
  {t:"The blade itself incites to deeds of violence.", a:"Homer · The Odyssey"},
  {t:"Sleep, delicious and profound, the very counterfeit of death.", a:"Homer · The Odyssey"},
  {t:"Few sons are like their fathers; most are worse, few indeed are better.", a:"Homer · The Odyssey"},
  {t:"All men have need of the gods.", a:"Homer · The Odyssey"},

  /* ---------------- Bhagavad Gita ---------------- */
  {t:"You have a right to your actions, but never to the fruits of your actions.", a:"Bhagavad Gita 2.47"},
  {t:"The soul is never born, nor does it ever die; it is unborn, eternal and everlasting.", a:"Bhagavad Gita 2.20"},
  {t:"As a man casts off worn-out garments and puts on new ones, so the soul casts off worn-out bodies and enters others that are new.", a:"Bhagavad Gita 2.22"},
  {t:"Whenever righteousness declines and unrighteousness rises, then I manifest myself.", a:"Bhagavad Gita 4.7"},
  {t:"The contacts of the senses give rise to heat and cold, pleasure and pain; they come and go, they are impermanent — endure them bravely.", a:"Bhagavad Gita 2.14"},
  {t:"Lift yourself by your own self; do not let yourself sink — for the self alone is the friend of the self, and the self alone is its enemy.", a:"Bhagavad Gita 6.5"},
  {t:"Better is one's own duty, though imperfectly done, than the duty of another well performed.", a:"Bhagavad Gita 3.35"},
  {t:"From attachment springs desire, and from desire arises anger.", a:"Bhagavad Gita 2.62"},
  {t:"Perform your duty with an even mind, abandoning attachment to success and failure — such evenness of mind is called yoga.", a:"Bhagavad Gita 2.48"},
  {t:"Whoever offers me with devotion a leaf, a flower, a fruit or water — that offering of love I accept.", a:"Bhagavad Gita 9.26"},
  {t:"As a lamp sheltered from the wind does not flicker, so is the disciplined mind absorbed in the self.", a:"Bhagavad Gita 6.19"},
  {t:"As rivers flow into the ocean, which is ever full and still, so all desires enter the sage who is unmoved — he attains peace.", a:"Bhagavad Gita 2.70"},
  {t:"There is nothing in this world so purifying as knowledge.", a:"Bhagavad Gita 4.38"},
  {t:"He who hates no being, who is friendly and compassionate to all, even-minded in pain and pleasure — he is dear to me.", a:"Bhagavad Gita 12.13"},
  {t:"A man is made by his faith: as his faith is, so is he.", a:"Bhagavad Gita 17.3"},
  {t:"For one moderate in food and recreation, moderate in action, moderate in sleep and waking, yoga destroys all sorrow.", a:"Bhagavad Gita 6.17"},

  /* ------- Nietzsche — Human, All Too Human (and after) ------- */
  {t:"Convictions are more dangerous enemies of truth than lies.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"There are no eternal facts, as there are no absolute truths.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"He who cannot put his thoughts on ice should not enter into the heat of dispute.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"The best author will be the one who is ashamed to become a writer.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"A good writer possesses not only his own spirit but also the spirit of his friends.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"Every habit lends our hand more wit, but makes our wit less handy.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"The irrationality of a thing is no argument against its existence, rather a condition of it.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"He who thinks a great deal is not suited to be a party man: he thinks his way through the party and out the other side too soon.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"Many a man fails as an original thinker simply because his memory is too good.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"The mother of excess is not joy but joylessness.", a:"Friedrich Nietzsche · Human, All Too Human"},
  {t:"He who has a why to live can bear almost any how.", a:"Friedrich Nietzsche · Twilight of the Idols"},
  {t:"You must have chaos within you to give birth to a dancing star.", a:"Friedrich Nietzsche · Thus Spoke Zarathustra"},

  /* -------- Dostoevsky — Crime and Punishment -------- */
  {t:"Pain and suffering are always inevitable for a large intelligence and a deep heart.", a:"Fyodor Dostoevsky · Crime and Punishment"},
  {t:"To go wrong in one's own way is better than to go right in someone else's.", a:"Fyodor Dostoevsky · Crime and Punishment"},
  {t:"Man grows used to everything, the scoundrel!", a:"Fyodor Dostoevsky · Crime and Punishment"},
  {t:"Power is given only to him who dares to stoop and pick it up.", a:"Fyodor Dostoevsky · Crime and Punishment"},
  {t:"Taking a new step, uttering a new word, is what people fear most.", a:"Fyodor Dostoevsky · Crime and Punishment"},
  {t:"When reason fails, the devil helps!", a:"Fyodor Dostoevsky · Crime and Punishment"},
  /* -------- Dostoevsky — The Brothers Karamazov -------- */
  {t:"Above all, do not lie to yourself.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  {t:"The man who lies to himself can be more easily offended than anyone.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  {t:"Love in action is a harsh and dreadful thing compared with love in dreams.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  {t:"Hell is the suffering of being unable to love.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  {t:"Love all God's creation, both the whole of it and every grain of sand. Love every leaf, every ray of God's light.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  {t:"Beauty is a terrible and awful thing — God and the devil are fighting there, and the battlefield is the heart of man.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  {t:"If there is no God, everything is lawful.", a:"Fyodor Dostoevsky · The Brothers Karamazov"},
  /* -------- Dostoevsky — The Idiot -------- */
  {t:"Beauty will save the world.", a:"Fyodor Dostoevsky · The Idiot"},
  {t:"Compassion is the chief and perhaps the only law of all human existence.", a:"Fyodor Dostoevsky · The Idiot"},
  {t:"It is better to be unhappy and know the worst, than to be happy in a fool's paradise.", a:"Fyodor Dostoevsky · The Idiot"},
  {t:"The causes of human actions are usually immeasurably more complex than our subsequent explanations of them.", a:"Fyodor Dostoevsky · The Idiot"},

  /* ------- François de La Rochefoucauld — Maxims ------- */
  {t:"Hypocrisy is the homage that vice pays to virtue.", a:"La Rochefoucauld · Maxims"},
  {t:"We all have strength enough to bear the misfortunes of others.", a:"La Rochefoucauld · Maxims"},
  {t:"True love is like a ghost: everyone talks of it, few have seen it.", a:"La Rochefoucauld · Maxims"},
  {t:"We are never so happy nor so unhappy as we imagine.", a:"La Rochefoucauld · Maxims"},
  {t:"Jealousy is born with love, but does not always die with it.", a:"La Rochefoucauld · Maxims"},
  {t:"If we had no faults, we should not take so much pleasure in noticing them in others.", a:"La Rochefoucauld · Maxims"},
  {t:"The surest way to be deceived is to think oneself cleverer than others.", a:"La Rochefoucauld · Maxims"},
  {t:"Everyone complains of his memory, and no one complains of his judgment.", a:"La Rochefoucauld · Maxims"},
  {t:"We often forgive those who bore us, but we cannot forgive those whom we bore.", a:"La Rochefoucauld · Maxims"},
  {t:"It is easier to be wise for others than for ourselves.", a:"La Rochefoucauld · Maxims"},
  {t:"The refusal of praise is a desire to be praised twice.", a:"La Rochefoucauld · Maxims"},
  {t:"We promise according to our hopes and perform according to our fears.", a:"La Rochefoucauld · Maxims"},
  {t:"Absence diminishes little passions and increases great ones, as the wind extinguishes candles and fans a fire.", a:"La Rochefoucauld · Maxims"},
  {t:"Few people know how to be old.", a:"La Rochefoucauld · Maxims"},
  {t:"Quarrels would not last long if the fault were only on one side.", a:"La Rochefoucauld · Maxims"},
  {t:"We rarely find that people have good sense unless they agree with us.", a:"La Rochefoucauld · Maxims"},
  {t:"Perfect valor is to do without witnesses what one would do before all the world.", a:"La Rochefoucauld · Maxims"},
  {t:"The mind is always the dupe of the heart.", a:"La Rochefoucauld · Maxims"},
  {t:"Silence is the best resolve for him who distrusts himself.", a:"La Rochefoucauld · Maxims"},
  {t:"One gives nothing so freely as advice.", a:"La Rochefoucauld · Maxims"},
  {t:"Our virtues are most frequently but vices in disguise.", a:"La Rochefoucauld · Maxims"},

  /* ---------------- Shiva Purana ---------------- */
  {t:"Bad conduct leads to misery and good conduct to happiness; hence it is the duty of everyone to acquire goodness.", a:"Shiva Purana"},
  {t:"Shiva is called the physician of the world by those who know the nature of the principles.", a:"Shiva Purana"},
  {t:"Listening to the glory of Shiva, glorifying him in words, and deliberation in the mind — these constitute the greatest of the means.", a:"Shiva Purana"},
  {t:"He is the atman of all; there is no greater atman than him.", a:"Shiva Purana"},
  {t:"Devotion leads to knowledge, and devotion joined with knowledge leads to liberation.", a:"Shiva Purana"},

  /* ---------------- Chanakya — Chanakya Niti ---------------- */
  {t:"Go to the forest and see: the straight trees are cut down, the crooked ones are left standing. Do not be too upright in your dealings.", a:"Chanakya · Chanakya Niti"},
  {t:"Education is the best friend; an educated person is respected everywhere.", a:"Chanakya · Chanakya Niti"},
  {t:"Before you start any work, ask yourself three questions: Why am I doing it? What might the results be? Will I be successful?", a:"Chanakya · Chanakya Niti"},
  {t:"As soon as fear approaches near, attack and destroy it.", a:"Chanakya · Chanakya Niti"},
  {t:"The fragrance of flowers spreads only in the direction of the wind, but the goodness of a person spreads in all directions.", a:"Chanakya · Chanakya Niti"},
  {t:"A man is great by deeds, not by birth.", a:"Chanakya · Chanakya Niti"},
  {t:"There is no austerity equal to a balanced mind, and no happiness equal to contentment.", a:"Chanakya · Chanakya Niti"},
  {t:"Even if a snake is not poisonous, it should pretend to be venomous.", a:"Chanakya · Chanakya Niti"},
  {t:"Never share your secrets with anybody — it will destroy you.", a:"Chanakya · Chanakya Niti"},
  {t:"Once you start working on something, do not be afraid of failure and do not abandon it. Those who work sincerely are the happiest.", a:"Chanakya · Chanakya Niti"},
  {t:"Time perfects men as well as destroys them.", a:"Chanakya · Chanakya Niti"},
  {t:"He who is overly attached experiences fear and sorrow, for the root of all grief is attachment.", a:"Chanakya · Chanakya Niti"},
  {t:"Do not reveal what you have thought upon doing; keep it secret by wise counsel, and carry it into execution.", a:"Chanakya · Chanakya Niti"},
  {t:"A person is born alone and dies alone, and experiences the fruits of his karma alone.", a:"Chanakya · Chanakya Niti"},
  {t:"Books are as useful to a stupid person as a mirror is useful to a blind person.", a:"Chanakya · Chanakya Niti"},

  /* ---------------- and a few more voices ---------------- */
  {t:"Simplicity is the ultimate sophistication.", a:"Leonardo da Vinci"},
  {t:"Learning never exhausts the mind.", a:"Leonardo da Vinci"},
  {t:"Water is the driving force of all nature.", a:"Leonardo da Vinci"},
  {t:"Time stays long enough for anyone who will use it.", a:"Leonardo da Vinci"},
  {t:"You have power over your mind — not outside events. Realize this, and you will find strength.", a:"Marcus Aurelius · Meditations"},
  {t:"The soul becomes dyed with the color of its thoughts.", a:"Marcus Aurelius · Meditations"},
  {t:"Waste no more time arguing about what a good man should be. Be one.", a:"Marcus Aurelius · Meditations"},
  {t:"It is not that we have a short time to live, but that we waste a lot of it.", a:"Seneca · On the Shortness of Life"},
  {t:"No man is free who is not master of himself.", a:"Epictetus"},
  {t:"What you seek is seeking you.", a:"Rumi"},
  {t:"The wound is the place where the light enters you.", a:"Rumi"},
  {t:"There is nothing either good or bad, but thinking makes it so.", a:"William Shakespeare · Hamlet"},
  {t:"We know what we are, but know not what we may be.", a:"William Shakespeare · Hamlet"},
  {t:"Love all, trust a few, do wrong to none.", a:"William Shakespeare · All's Well That Ends Well"},
  {t:"No man ever steps in the same river twice.", a:"Heraclitus"},
  {t:"A journey of a thousand miles begins with a single step.", a:"Lao Tzu · Tao Te Ching"},
  {t:"Nature does not hurry, yet everything is accomplished.", a:"Lao Tzu"},
  {t:"It does not matter how slowly you go as long as you do not stop.", a:"Confucius"},
  {t:"The man who moves a mountain begins by carrying away small stones.", a:"Confucius"},
  {t:"Dripping water hollows out stone, not through force but through persistence.", a:"Ovid"},
  {t:"Fortune favors the bold.", a:"Virgil · Aeneid"},
  {t:"Life is short, and art long.", a:"Hippocrates"},
];
